### ISSUE TITLE
Getting Error when running Server script from application folder

### ISSUE THREAD

**Issue by cybertheory** [aggarwalpiush/goodBadNewsTweet#1]
Hi, I am trying to use this script to classify text into good and bad news! I am trying to run the server script and it works perfectly. However, when I use the client script to send the example request it gives me the following error.

```
API Exception: {'type': 'FileNotFoundError', 'args': (2, 'No such file or directory'), 'message': "[Errno 2] No such file or directory: 'crawl-300d-2M.vec'"}
Traceback (most recent call last):
  File "C:\Users\guest\Anaconda3\lib\site-packages\jsonrpc\manager.py", line 113, in _get_responses
    result = method(*request.args, **request.kwargs)
  File "good_bad_news_predict_server.py", line 66, in get_request
    tweet_transform = get_embedding_vector(tokenized_tweet_text, 'crawl-300d-2M.vec').reshape(1,-1)
  File "good_bad_news_predict_server.py", line 41, in get_embedding_vector
    embeddings =  get_embedding_dictionary(embedding_file)
  File "good_bad_news_predict_server.py", line 27, in get_embedding_dictionary
    with codecs.open(embedding_file, 'r', encoding="utf8") as file:
  File "C:\Users\guest\Anaconda3\lib\codecs.py", line 898, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'crawl-300d-2M.vec'
127.0.0.1 - - [06/May/2020 11:42:58] "POST /jsonrpc HTTP/1.1" 200 -
```
I cant seem to find that file anywhere! Can anyone help me with this? Thanks!

edit: I think this is an external token file you have to download... maybe from here? https://fasttext.cc/docs/en/english-vectors.html

**Comment by cybertheory** [comment]
I got the analysis script to work. How should we interpret the results? Is closer to 1 good news or bad news? What about the news vs no news classifier? Please let me know!
